# This is a basic workflow to help you get started with Actions

name: Comment On Un-reviewed PRs

# Controls when the action will run. 
on:
  schedule:
    - cron:  '0 10,15 * * MON,TUE,WED,THU,FRI'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: |
          python comment-on-unreviewed.py
        env:
          TOKEN: ${{ secrets.token }}
